### ISSUE TITLE
Remove the Sllyabus and the Schedule

### ISSUE THREAD

**Issue by KevenDuverglas** [TeamDevDev/www.developerdevelopment.com#40]
This is likely the final issue to address in order to give the website a more blog-like appearance. Additionally, we can enhance the website by adding an 'About Us' section.

**Comment by gkapfham** [comment]
Hello @KevenDuverglas, I don't think that we should ultimately remove the syllabus or the schedule as they are key parts of the class. I am also hopeful that we can re-use some of the content in this web site when the class is taught the next time around. As such, we will probably again need a schedule and a syllabus. Thus, I am going to close this issue. If you think that it really needs to be addressed, please consider opening it again. Thanks!
