### ISSUE TITLE
Assesment Date Error

### ISSUE THREAD

**Issue by TitusSmith33** [TeamDevDev/www.developerdevelopment.com#64]
The 'Schedule' tab for our course website, in schedule/index.qmd, it notes that our final exam--under Exam Code G-- is Thursday, December 11th, 2024 at 9:00am. While this course is under Exam Code G, the correct date for that exam is **Wednesday** 11th, 2024 at 9:00 am. For more information on the Exam Codes, see the following [link](https://sites.allegheny.edu/registrar/fall-2024-final-exam-schedule/).

**Comment by gkapfham** [comment]
Hello @TitusSmith33 I have resolved this issue, thanks for reporting it!
